apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  sentiment-analysis
  labels:
    app:   sentiment-analysis
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  
  template:
    metadata:
      labels:
        app:  sentiment-analysis
    spec: 
      containers:
      - image:  k8s-sentiment-analysis
        name:  sentiment-analysis
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /status
            port: 8000
        ports:
        - containerPort:  8000
        volumeMounts:
        - mountPath: /sentiment-analysis
          name: sentiment-analysis
      volumes:
      - name: sentiment-analysis
        configMap:
          name: sentiment-analysis
          defaultMode: 0400
